/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:b24c8c4a-fd7d-4156-8105-f1f97b76f0a1",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_QYI31lCR2",
    "aws_user_pools_web_client_id": "3oev08kmc8kl4qv3624p37f14s",
    "oauth": {
        "domain": "theveganmanna347effdd-347effdd-dev.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://www.veganmanna.org/,https://www.veganmanna.org/",
        "redirectSignOut": "https://www.veganmanna.org/,https://www.veganmanna.org/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://fbhj5z6o7zcu7a6uzvqvocud4u.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-up7d7pi3s5czzivwjtz2vpkabm",
    "aws_cloud_logic_custom": [
        {
            "name": "s3Upload",
            "endpoint": "https://7k3v8a8bzh.execute-api.eu-west-2.amazonaws.com/dev",
            "region": "eu-west-2"
        },
        {
            "name": "nutrition",
            "endpoint": "https://kgtfhaibnj.execute-api.eu-west-2.amazonaws.com/dev",
            "region": "eu-west-2"
        },
        {
            "name": "instagram",
            "endpoint": "https://iceb70oflh.execute-api.eu-west-2.amazonaws.com/dev",
            "region": "eu-west-2"
        }
    ],
    "aws_user_files_s3_bucket": "theveganmanna-recipecontent121823-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
